### ISSUE TITLE
Polybar module disables if it starts earlier than dwm

### ISSUE THREAD

**Issue by gitneeraj** [mihirlad55/polybar-dwm-module#17] opened 2020-08-04 08:37 UTC
## Describe the issue
I did follow the instructions in this repo to add Polybar to my dwm. So I applied all my patches to dwm first then anybar patch and finally IPC patch. Restarted my sys and I could see the polybar. It all worked fine.

But as soon as I made some more changes to my dwm's config.def.h(basically renamed my tags) and re-built my dwm, suddenly dwm's tags wont show up on Polybar. I could still see other modules even after system restart.

**Expected behavior:**
Should show tags even after applying patches after IPC patch
![dwm_polybar_desktop](https://user-images.githubusercontent.com/36226187/89272704-2851b480-d65c-11ea-99a9-b5b93d51e759.png)

*What actually happens*
![dwm-no-tags](https://user-images.githubusercontent.com/36226187/89272748-3e5f7500-d65c-11ea-8981-574908e53f46.png)

## To Reproduce
DWM build - https://github.com/gitneeraj/dwm_polybar
Polybar config - https://github.com/gitneeraj/dotfiles/blob/master/polybar/config

## Environment:
* WM: DWM
* Distro: Artix linux with OpenRC init
* Output of `polybar -vvv`:
```
polybar 3.4.0-197-g62fca24

Features: +alsa +curl +dwm +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

```

**Comment by isyuck** [comment] 2020-08-04 10:06
i have a similar issue, a quick fix that worked for me was starting polybar after dwm when Xorg starts. my .xinitrc calls a script before dwm (running in background with &) that sleeps for a second, then starts polybar as per my usual config.

this is by no means a solution, though.

**Comment by gitneeraj** [comment] 2020-08-04 11:50
Yes, at the moment even i am handling the same way.

**Comment by mihirlad55** [comment] 2020-08-04 19:17
If the problem is polybar starting too early, the ugly solution is just extending the delay before polybar starts. However, since there are many people who are reporting this issue, I may have a solution.

If dwm launches polybar after it is ready and initialized, then this issue shouldn't happen and there would be no need for hardcoded delays. Now the question is, does this type of patch already exist? If not, would this patch make most sense as:
- A standalone patch
- Part of `dwm-anybar`
- Part of `dwm-ipc`

I'm leaning towards a standalone patch, since this can be helpful in numerous situations and I'd rather not force people to use these other larger patches for this simple purpose.

I'll take a look to see if something like this already exists. If not, I might have something ready by the end of the day. I'll also update the README with "launching polybar" instructions.

**Comment by mihirlad55** [comment] 2020-08-04 19:50
So, I found this patch which seems to already do what I'm talking about:
https://dwm.suckless.org/patches/autostart/

If you add your polybar start command in `~/.dwm/autostart.sh` after applying the patch, it should fix this issue. Try that and let me know if it works.

**Comment by mihirlad55** [comment] 2020-08-10 01:40
See commit
https://github.com/mihirlad55/dwm-anybar/commit/6a8285817494ebd8b12605baebd8d924820670e0

**Comment by mihirlad55** [comment] 2020-08-10 01:42
Since the autostart patch is a bit more than what would be necessary to simply launch a bar, I decided to add a quick update to dwm-anybar that allows you to specify the path to your bar launch script. This method of launching should ensure that the bar does not start too early. Let me know if this works for you. As of right now, three fixes for this issue are:
- autostart patch
- anybar patch
- startup delay

**Comment by mihirlad55** [comment] 2020-08-10 01:57
I've updated the README as well with instructions. See commit 89c530d

**Comment by mihirlad55** [comment] 2020-08-11 19:56
Let me know if you guys are satisfied with these solutions. If I don't hear back soon, I'll be closing this issue.

**Closed as completed** 2020-08-15 17:31 UTC
